version: '3.8'

services:
  appseed-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: appseed_app_dev
    ports:
      - "5005:5005"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - FLASK_APP=run.py
    networks:
      - web_network
      - db_network
    depends_on:
      mysql:
        condition: service_healthy
    command: >
      sh -c "
        flask db init || true &&
        flask db migrate -m 'Initial migration' || true &&
        flask db upgrade &&
        flask run --host=0.0.0.0 --port=5005 --reload
      "

  mysql:
    image: mysql:8.0
    container_name: mysql_dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hub_mconfea
      MYSQL_USER: hub_user
      MYSQL_PASSWORD: hub_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - db_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 20

  nginx:
    container_name: nginx_dev
    image: nginx:latest
    ports:
      - "5085:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on:
      - appseed-app

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge

volumes:
  mysql_data: