FROM python:3.10

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV FLASK_APP run.py
ENV FLASK_DEBUG 1

WORKDIR /app

COPY requirements.txt .

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# CMD ["gunicorn", "--config", "gunicorn-cfg.py", "run:app"]
CMD ["flask", "run", "--host=0.0.0.0", "--port=5005", "--reload"]
