version: '3.8'

services:
  appseed-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: appseed-app
    volumes:
      - .:/app
    ports:
      - "5085:5005"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    command: >
      sh -c "
      flask db init || true &&
      flask db migrate -m 'Initial migration' || true &&
      flask db upgrade &&
      flask run --host=0.0.0.0 --port=5005 --reload
      "
    depends_on:
      - mysql
    networks:
      - db_network
      - web_network